### PR TITLE
fix freertos submodule link

### PR DESCRIPTION
**Pull request by dariosb**
`git submodule add -- /url/of/sub1/repo sub1`
On the other hand, AWS Freertos repo is too big and gets too much time updating when first time download.
This wait would be propagated to RKH repo cloning when synching submodules....
Optionally, only get **freertos/freertos_kernel** repo as submodule may be better.

Adds **BOARD** environment variable definition for **Debug_EDU_CIAA-NXP** and **Debug_CIAA-NXP** builds.

### CODE REVIEW

**Comment by cmancon** [comment]
I'm up for changing the submodule to the kernel only. What do you think about it @leanfrancucci ?

**Comment by cmancon** [comment]
Changed the submodule to the kernel-only version to evaluate the impact. 

The result of the cloning is around **103Mb** in objects:
```
$ git submodule add https://github.com/FreeRTOS/FreeRTOS-Kernel.git third-party/freertos/freertos_kernel
Cloning into '/home/cmancon/RKH/third-party/freertos/freertos_kernel'...
remote: Enumerating objects: 148185, done.
remote: Total 148185 (delta 0), reused 0 (delta 0), pack-reused 148185
Receiving objects: 100% (148185/148185), 102.95 MiB | 3.46 MiB/s, done.
Resolving deltas: 100% (107371/107371), done.
```

Also, I've checked that the environment variables are being tracked, and had success compiling with each build configurations (**Debug_EDU_CIAA-NXP** and **Debug_CIAA-NXP**).

**Comment by leanfrancucci** [comment]
> I'm up for changing the submodule to the kernel only. What do you think about it @leanfrancucci ?

I agree with that. A submodule is only downloaded when you need it, so when one clone RKH repo there is no need to download all associated submodules as well.

**Comment by cmancon** [comment]
All parties agree then!
@dariosb is there any other commit to include to this PR? I've none. I think we are good to proceed with the closing and merge.

**Comment by cmancon** [comment]
Added a commit to correct a possible compilation error. It wasn't specific to this branch but this is the more developed one.

**Comment by cmancon** [comment]
I'm thinking in merge this PR in 24hs if none of you have any complain or concern to raise, @dariosb, @leanfrancucci .

**Comment by dariosb** [comment]
Its ok for me

**Pull request merged**
